<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GestanteSeeder extends Seeder
{
    /**
     * Gestantes de prueba con coordenadas reales de Ucayali.
     * Listo para reemplazar con datos de SQL Server cuando los entreguen.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $gestantes = [
            [
                'tipo_documento'       => 'DNI',
                'numero_documento'     => '45231890',
                'nombre'               => 'María Elena',
                'apellido_paterno'     => 'Ríos',
                'apellido_materno'     => 'Valera',
                'fecha_nacimiento'     => '1998-03-14',
                'telefono'             => '961234567',
                'ubigeo'               => '250101',
                'region'               => 'Ucayali',
                'provincia'            => 'Coronel Portillo',
                'distrito'             => 'Callería',
                'direccion'            => 'Jr. Ucayali 342',
                'latitud'              => -8.3791,
                'longitud'             => -74.5539,
                'estado'               => 'Emergencia',
                'nivel_gravedad'       => 'Grave',
                'semanas_gestacion'    => 38,
                'fecha_registro'       => $now->copy()->subHours(2),
                'fecha_atendido'       => null,
                'fecha_finalizado'     => null,
                'reporte'              => 'Presenta sangrado y contracciones intensas.',
                'informacion_declarada'=> 'Dolor fuerte desde hace 3 horas.',
            ],
            [
                'tipo_documento'       => 'DNI',
                'numero_documento'     => '47891023',
                'nombre'               => 'Rosa',
                'apellido_paterno'     => 'Sánchez',
                'apellido_materno'     => 'Pérez',
                'fecha_nacimiento'     => '2001-07-22',
                'telefono'             => '962345678',
                'ubigeo'               => '250102',
                'region'               => 'Ucayali',
                'provincia'            => 'Coronel Portillo',
                'distrito'             => 'Manantay',
                'direccion'            => 'Av. Centenario 1120',
                'latitud'              => -8.4050,
                'longitud'             => -74.5890,
                'estado'               => 'Pendiente',
                'nivel_gravedad'       => 'Leve',
                'semanas_gestacion'    => 28,
                'fecha_registro'       => $now->copy()->subMinutes(45),
                'fecha_atendido'       => null,
                'fecha_finalizado'     => null,
                'reporte'              => 'Control prenatal programado.',
                'informacion_declarada'=> 'Hinchazón en pies desde ayer.',
            ],
            [
                'tipo_documento'       => 'DNI',
                'numero_documento'     => '43567812',
                'nombre'               => 'Lucia',
                'apellido_paterno'     => 'Flores',
                'apellido_materno'     => 'Torres',
                'fecha_nacimiento'     => '1995-11-05',
                'telefono'             => '963456789',
                'ubigeo'               => '250103',
                'region'               => 'Ucayali',
                'provincia'            => 'Coronel Portillo',
                'distrito'             => 'Yarinacocha',
                'direccion'            => 'Jr. Los Pinos 567',
                'latitud'              => -8.2890,
                'longitud'             => -74.4980,
                'estado'               => 'Atendida',
                'nivel_gravedad'       => 'Normal',
                'semanas_gestacion'    => 20,
                'fecha_registro'       => $now->copy()->subDays(1),
                'fecha_atendido'       => $now->copy()->subHours(18),
                'fecha_finalizado'     => null,
                'reporte'              => 'Control rutinario completado sin novedad.',
                'informacion_declarada'=> 'Sin molestias. Embarazo normal.',
            ],
            [
                'tipo_documento'       => 'DNI',
                'numero_documento'     => '48901234',
                'nombre'               => 'Ana',
                'apellido_paterno'     => 'Vásquez',
                'apellido_materno'     => 'Huamán',
                'fecha_nacimiento'     => '2000-01-30',
                'telefono'             => '964567890',
                'ubigeo'               => '250201',
                'region'               => 'Ucayali',
                'provincia'            => 'Atalaya',
                'distrito'             => 'Raymondi',
                'direccion'            => 'Av. Atalaya 220',
                'latitud'              => -10.7295,
                'longitud'             => -73.7693,
                'estado'               => 'Pendiente',
                'nivel_gravedad'       => 'Leve',
                'semanas_gestacion'    => 36,
                'fecha_registro'       => $now->copy()->subHours(1),
                'fecha_atendido'       => null,
                'fecha_finalizado'     => null,
                'reporte'              => 'Presión arterial elevada. Requiere seguimiento.',
                'informacion_declarada'=> 'Dolor de cabeza y visión borrosa.',
            ],
            [
                'tipo_documento'       => 'DNI',
                'numero_documento'     => '44678902',
                'nombre'               => 'Carmen',
                'apellido_paterno'     => 'Ruiz',
                'apellido_materno'     => 'Mamani',
                'fecha_nacimiento'     => '1993-08-17',
                'telefono'             => '965678901',
                'ubigeo'               => '250301',
                'region'               => 'Ucayali',
                'provincia'            => 'Padre Abad',
                'distrito'             => 'Padre Abad',
                'direccion'            => 'Jr. Aguaytía 450',
                'latitud'              => -9.0393,
                'longitud'             => -75.5186,
                'estado'               => 'Atendida',
                'nivel_gravedad'       => 'Leve',
                'semanas_gestacion'    => 32,
                'fecha_registro'       => $now->copy()->subDays(2),
                'fecha_atendido'       => $now->copy()->subDays(2)->addHours(3),
                'fecha_finalizado'     => $now->copy()->subDays(1),
                'reporte'              => 'Caso cerrado exitosamente.',
                'informacion_declarada'=> 'Se recuperó bien. Sin complicaciones.',
            ],
            [
                'tipo_documento'       => 'CE',
                'numero_documento'     => 'CE001234',
                'nombre'               => 'Diana',
                'apellido_paterno'     => 'Guerrero',
                'apellido_materno'     => null,
                'fecha_nacimiento'     => '1999-05-12',
                'telefono'             => '966789012',
                'ubigeo'               => '250104',
                'region'               => 'Ucayali',
                'provincia'            => 'Coronel Portillo',
                'distrito'             => 'Campo Verde',
                'direccion'            => 'Carretera Campo Verde Km 12',
                'latitud'              => -8.6012,
                'longitud'             => -74.8543,
                'estado'               => 'Emergencia',
                'nivel_gravedad'       => 'Grave',
                'semanas_gestacion'    => 40,
                'fecha_registro'       => $now->copy()->subMinutes(20),
                'fecha_atendido'       => null,
                'fecha_finalizado'     => null,
                'reporte'              => 'Parto inminente. Traslado urgente a hospital.',
                'informacion_declarada'=> 'Contracciones cada 2 minutos.',
            ],
        ];

        DB::table('gestantes')->insert($gestantes);
    }
}